AssetsVersion: 8f4ae0b86da5dd7475cb64dd25dccff815791526
AssetsServerBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
OutcomesServerBaseURL: https://qyikpc6uniqdv45wk65iy3a2c40qbhtk.lambda-url.us-west-2.on.aws/
ServerBaseURL: https://gateway.snapser.com/xbeovm9i/v1
MainBundleName: main
MainBundleVariant: v0_1_0
UseFileSystemAssetBundles: true
UseFileSystemOutcomes: true
UseLocalServer: false
