AssetsVersion: latest
AssetsServerBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
AudioServerBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
VideoServerBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
OutcomesServerBaseURL: https://3wcgnl14qb.execute-api.us-west-2.amazonaws.com/gateway
ServerBaseURL: https://gateway.snapser.com/xbeovm9i/v1
UseFileSystemAssetBundles: false
UseFileSystemAudio: false
UseFileSystemVideo: false
UseFileSystemOutcomes: false
UseLocalServer: false
